# -*- coding: utf-8 -*-
import logging

from . import Module
from . import custom_tags as ct

logger = logging.getLogger(__name__)
logger.addHandler(logging.NullHandler())


class CallModule(Module):
    """
    Data related to a call.
    Types of Call Modules:
    0 - Transit
    1 - MSOriginating
    2 - RoamingCallForwarding
    3 - CallForwarding
    4 - MSTerminating
    5 - MSOriginatingSMSinMSC
    6 - MSOriginatingSMSinSMS-IWMSC
    7 - MSTerminatingSMSinMSC
    8 - MSTerminatingSMSinSMS-GMSC
    9 - SSProcedure
    13 - TransitINOutgoingCall
    14 - INIncomingCall
    15 - INOutgoingCall
    17 - ISDNOriginating
    18 - ISDNCallForwarding
    19 - ISDNSSProcedure
    21 - SCFChargingOutput
    24 - LocationServices
    """

    def __init__(self, tag=None, byte_string=None):
        super(CallModule, self).__init__(tag, byte_string)

    def __repr__(self):
        return "Call Module - {} ({})".format(self.__class__.__name__, self.tag.header.number)


class Transit(CallModule):
    _data_tag_types = {0: (ct.TAC, None),
                       1: (ct.CallIDNumber, None),
                       2: (ct.RecordSequenceNumber, None),
                       3: (ct.TypeOfCallingSubscriber, None),
                       4: (ct.AddressString, "callingPartyNumber"),
                       5: (ct.AddressString, "calledPartyNumber"),
                       6: (ct.IMSI, "calledSubscriberIMSI"),
                       7: (ct.DisconnectingParty, None),
                       8: (ct.Date, "dateForStartOfCharge"),
                       9: (ct.Time, "timeForStartOfCharge"),
                       10: (ct.Time, "timeForStopOfCharge"),
                       11: (ct.Time, "chargeableDuration"),
                       12: (ct.Time, "interruptionTime"),
                       13: (ct.Time, "timeFromRegisterSeizureToStartOfCharging"),
                       14: (ct.ChargedParty, None),
                       15: (ct.ChargingOrigin, None),
                       16: (ct.TariffClass, None),
                       17: (ct.TariffSwitchInd, None),
                       18: (ct.NumberOfMeterPulses, None),
                       19: (ct.ExchangeIdentity, None),
                       20: (ct.AddressString, "mSCIdentification"),
                       21: (ct.Route, "outgoingRoute"),
                       22: (ct.Route, "incomingRoute"),
                       23: (ct.MiscellaneousInformation, None),
                       25: (ct.INMarkingOfMS, None),
                       26: (ct.CallPosition, None),
                       27: (ct.EosInfo, None),
                       28: (ct.InternalCauseAndLoc, None),
                       29: (ct.AddressString, "originalCalledNumber"),
                       30: (ct.AddressString, "redirectingNumber"),
                       31: (ct.RedirectionCounter, None),
                       32: (ct.AddressString, "redirectingDropBackNumber"),
                       33: (ct.Tag, "redirectingDropBack"),
                       34: (ct.Tag, "restartDuringCall"),
                       35: (ct.Tag, "restartDuringOutputIndicator"),
                       36: (ct.Tag, "iCIOrdered"),
                       37: (ct.OutputForSubscriber, None),
                       38: (ct.Tag, "lastPartialOutput"),
                       39: (ct.PartialOutputRecNum, None),
                       40: (ct.CallIDNumber, "relatedCallNumber"),
                       41: (ct.FaultCode, None),
                       42: (ct.SubscriptionType, None),
                       43: (ct.Tag, "incompleteCallDataIndicator"),
                       44: (ct.Tag, "incompleteCompositeCDRIndicator"),
                       45: (ct.SwitchIdentity, None),
                       46: (ct.NetworkCallReference, None),
                       47: (ct.Tag, "disconnectionDueToSystemRecovery"),
                       48: (ct.Tag, "forloppDuringOutputIndicator"),
                       49: (ct.Tag, "forloppReleaseDuringCall"),
                       50: (ct.AddressString, "translatedNumber"),
                       51: (ct.CAMELTDPData, "bCSMTDPData1"),
                       52: (ct.CAMELTDPData, "bCSMTDPData2"),
                       53: (ct.CAMELTDPData, "bCSMTDPData3"),
                       54: (ct.CAMELTDPData, "bCSMTDPData4"),
                       55: (ct.CAMELTDPData, "bCSMTDPData5"),
                       56: (ct.CAMELTDPData, "bCSMTDPData6"),
                       57: (ct.CAMELTDPData, "bCSMTDPData7"),
                       58: (ct.CAMELTDPData, "bCSMTDPData8"),
                       59: (ct.CAMELTDPData, "bCSMTDPData9"),
                       60: (ct.CAMELTDPData, "bCSMTDPData10"),
                       61: (ct.GSMCallReferenceNumber, None),
                       62: (ct.C7ChargingMessage, None),
                       63: (ct.C7CHTMessage, "c7FirstCHTMessage"),
                       64: (ct.C7CHTMessage, "c7SecondCHTMessage"),
                       65: (ct.ChargingIndicator, "aCMChargingIndicator"),
                       66: (ct.ChargingIndicator, "aNMChargingIndicator"),
                       67: (ct.AddressString, "mSCAddress"),
                       68: (ct.TransitCarrierInfo, "carrierInformationBackward"),
                       69: (ct.TransitCarrierInfo, "carrierInformationForward"),
                       70: (ct.ChargeInformation, None),
                       71: (ct.Date, "disconnectionDate"),
                       72: (ct.Time, "disconnectionTime"),
                       73: (ct.ChargeAreaCode, "entryPOICA"),
                       74: (ct.ChargeAreaCode, "exitPOICA"),
                       75: (ct.Tag, "internationalCallIndicator"),
                       76: (ct.MobileUserClass1, "mobileUserClass1"),
                       77: (ct.MobileUserClass2, "mobileUserClass2"),
                       78: (ct.Tag, "originatingAccessISDN"),
                       79: (ct.CarrierInfo, "originatingCarrier"),
                       80: (ct.ChargeAreaCode, "originatingChargeArea"),
                       81: (ct.Counter, "tDSCounter"),
                       82: (ct.Tag, "terminatingAccessISDN"),
                       83: (ct.CarrierInfo, "terminatingCarrier"),
                       84: (ct.ChargeAreaCode, "terminatingChargeArea"),
                       85: (ct.MobileUserClass1, "terminatingMobileUserClass1"),
                       86: (ct.MobileUserClass2, "terminatingMobileUserClass2"),
                       87: (ct.AddressString, "contractorNumber"),
                       88: (ct.UserClass, "terminatingUserClass"),
                       89: (ct.UserClass, None),
                       90: (ct.AddressString, "calledPartyMNPInfo"),
                       91: (ct.AddressString, "chargeNumber"),
                       92: (ct.OriginatingLineInformation, None),
                       93: (ct.MultimediaInformation, None),
                       94: (ct.GlobalCallReference, None),
                       95: (ct.Tag, "rTCIndicator"),
                       96: (ct.RTCSessionID, None),
                       97: (ct.RTCDefaultServiceHandling, None),
                       98: (ct.RTCFailureIndicator, None),
                       99: (ct.RTCNotInvokedReason, None),
                       100: (ct.AddressString, "calledDirectoryNumber"),
                       101: (ct.PChargingVector, "incomingPChargingVector"),
                       102: (ct.OutputType, None),
                       103: (ct.PChargingVector, "outgoingPChargingVector"),
                       24: (ct.OriginatedCode, None),
                       121: (ct.Tag, "reroutingIndicator")
    }

    def __init__(self, tag=None, byte_string=None):
        super(Transit, self).__init__(tag, byte_string)


class MSOriginating(CallModule):
    _data_tag_types = {0: (ct.TAC, None),
                       1: (ct.CallIDNumber, None),
                       2: (ct.RecordSequenceNumber, None),
                       3: (ct.TypeOfCallingSubscriber, None),
                       4: (ct.AddressString, "callingPartyNumber"),
                       5: (ct.IMSI, "callingSubscriberIMSI"),
                       6: (ct.IMEI, "callingSubscriberIMEI"),
                       7: (ct.AddressString, "calledPartyNumber"),
                       8: (ct.DisconnectingParty, "disconnectingParty"),
                       9: (ct.Date, "dateForStartOfCharge"),
                       10: (ct.Time, "timeForStartOfCharge"),
                       11: (ct.Time, "timeForStopOfCharge"),
                       12: (ct.Time, "chargeableDuration"),
                       13: (ct.Time, "interruptionTime"),
                       14: (ct.Time, "timeFromRegisterSeizureToStartOfCharging"),
                       15: (ct.ChargedParty, None),
                       16: (ct.ChargingOrigin, None),
                       17: (ct.ChargingCase, None),
                       18: (ct.TariffClass, None),
                       19: (ct.TariffSwitchInd, None),
                       20: (ct.ExchangeIdentity, None),
                       21: (ct.AddressString, "mSCIdentification"),
                       22: (ct.Route, "outgoingRoute"),
                       23: (ct.Route, "incomingRoute"),
                       24: (ct.MiscellaneousInformation, None),
                       25: (ct.AddressString, "originatingLocationNumber"),
                       26: (ct.Time, "timeForTCSeizureCalling"),
                       27: (ct.LocationInformation, "firstCallingLocationInformation"),
                       28: (ct.LocationInformation, "lastCallingLocationInformation"),
                       29: (ct.TeleServiceCode, None),
                       30: (ct.BearerServiceCode, None),
                       31: (ct.TransparencyIndicator, None),
                       32: (ct.FirstRadioChannelUsed, None),
                       33: (ct.CallPosition, None),
                       34: (ct.EosInfo, None),
                       35: (ct.InternalCauseAndLoc, None),
                       36: (ct.Tag, "restartDuringCall"),
                       37: (ct.Tag, "restartDuringOutputIndicator"),
                       38: (ct.NumberOfMeterPulses, None),
                       39: (ct.C7ChargingMessage, None),
                       40: (ct.C7CHTMessage, "c7FirstCHTMessage"),
                       41: (ct.C7CHTMessage, "c7SecondCHTMessage"),
                       42: (ct.AddressString, "calledPartyMNPInfo"),
                       43: (ct.CarrierIdentificationCode, None),
                       44: (ct.Tag, "dTMFUsed"),
                       45: (ct.Tag, "iCIOrdered"),
                       46: (ct.OutputForSubscriber, None),
                       47: (ct.INMarkingOfMS, None),
                       48: (ct.Tag, "lastPartialOutput"),
                       49: (ct.PartialOutputRecNum, None),
                       50: (ct.CUGInterlockCode, None),
                       51: (ct.CUGIndex, None),
                       52: (ct.Tag, "cUGOutgoingAccessUsed"),
                       53: (ct.Tag, "cUGOutgoingAccessIndicator"),
                       54: (ct.RegionalServiceUsed, None),
                       55: (ct.ChargingOrigin, "regionDependentChargingOrigin"),
                       56: (ct.SSCode, None),
                       57: (ct.ChannelAllocationPriorityLevel, None),
                       58: (ct.RadioChannelProperty, None),
                       59: (ct.FaultCode, None),
                       60: (ct.IntermediateRate, None),
                       61: (ct.SpeechCoderVersion, "firstAssignedSpeechCoderVersion"),
                       62: (ct.SpeechCoderPreferenceList, "speechCoderPreferenceList"),
                       63: (ct.SubscriptionType, None),
                       64: (ct.Tag, "incompleteCallDataIndicator"),
                       65: (ct.Tag, "incompleteCompositeCDRIndicator"),
                       67: (ct.SwitchIdentity, None),
                       68: (ct.NetworkCallReference, None),
                       69: (ct.FrequencyBandSupported, None),
                       70: (ct.Tag, "disconnectionDueToSystemRecovery"),
                       71: (ct.Tag, "forloppDuringOutputIndicator"),
                       72: (ct.Tag, "forloppReleaseDuringCall"),
                       73: (ct.AccountCode, None),
                       74: (ct.AddressString, "translatedNumber"),
                       75: (ct.CAMELTDPData, "bCSMTDPData1"),
                       76: (ct.CAMELTDPData, "bCSMTDPData2"),
                       77: (ct.CAMELTDPData, "bCSMTDPData3"),
                       78: (ct.CAMELTDPData, "bCSMTDPData4"),
                       79: (ct.CAMELTDPData, "bCSMTDPData5"),
                       80: (ct.CAMELTDPData, "bCSMTDPData6"),
                       81: (ct.CAMELTDPData, "bCSMTDPData7"),
                       82: (ct.CAMELTDPData, "bCSMTDPData8"),
                       83: (ct.CAMELTDPData, "bCSMTDPData9"),
                       84: (ct.CAMELTDPData, "bCSMTDPData10"),
                       85: (ct.GSMCallReferenceNumber, None),
                       86: (ct.AddressString, "mSCAddress"),
                       87: (ct.EMLPPPriorityLevel, None),
                       88: (ct.PositionAccuracy, None),
                       89: (ct.UserTerminalPosition, None),
                       90: (ct.ChannelCodings, "acceptableChannelCodings"),
                       91: (ct.Route, "incomingAssignedRoute"),
                       92: (ct.ChannelCodings, "channelCodingUsed"),
                       93: (ct.RANAPCauseCode, None),
                       94: (ct.AddressString, "gsmSCFAddress"),
                       95: (ct.FixedNetworkUserRate, "fNURRequested"),
                       96: (ct.AirInterfaceUserRate, "aIURRequested"),
                       97: (ct.NumberOfChannels, "numberOfChannelsRequested"),
                       98: (ct.BSSMAPCauseCode, None),
                       99: (ct.Tag, "multimediaCall"),
                       100: (ct.BitRate, "guaranteedBitRate"),
                       101: (ct.TariffClass, None),
                       102: (ct.OutputType, None),
                       103: (ct.TargetRNCid, "rNCidOfFirstRNC"),
                       104: (ct.BitRate, "maxBitRateDownlink"),
                       105: (ct.BitRate, "maxBitRateUplink"),
                       106: (ct.TransferDelay, None),
                       107: (ct.DeliveryOfErroneousSDU, "deliveryOfErroneousSDU1"),
                       108: (ct.DeliveryOfErroneousSDU, "deliveryOfErroneousSDU2"),
                       109: (ct.DeliveryOfErroneousSDU, "deliveryOfErroneousSDU3"),
                       110: (ct.ErrorRatio, "residualBitErrorRatio1"),
                       111: (ct.ErrorRatio, "residualBitErrorRatio2"),
                       112: (ct.ErrorRatio, "residualBitErrorRatio3"),
                       113: (ct.ErrorRatio, "sDUErrorRatio1"),
                       114: (ct.ErrorRatio, "sDUErrorRatio2"),
                       115: (ct.ErrorRatio, "sDUErrorRatio3"),
                       116: (ct.ChargingIndicator, "aCMChargingIndicator"),
                       117: (ct.ChargingIndicator, "aNMChargingIndicator"),
                       118: (ct.TransitCarrierInfo, "carrierInformationBackward"),
                       119: (ct.ChargeInformation, None),
                       120: (ct.Date, "disconnectionDate"),
                       124: (ct.Time, "disconnectionTime"),
                       125: (ct.CarrierInfo, "originatingCarrier"),
                       126: (ct.ChargeAreaCode, "originatingChargeArea"),
                       127: (ct.Counter, "tDSCounter"),
                       128: (ct.Tag, "terminatingAccessISDN"),
                       129: (ct.CarrierInfo, "terminatingCarrier"),
                       130: (ct.ChargeAreaCode, "terminatingChargeArea"),
                       131: (ct.MobileUserClass1, "terminatingMobileUserClass1"),
                       132: (ct.MobileUserClass2, "terminatingMobileUserClass2"),
                       133: (ct.UserClass, "terminatingUserClass"),
                       134: (ct.AddressString, "contractorNumber"),
                       135: (ct.CarrierInformation, None),
                       136: (ct.CarrierSelectionSubstitutionInformation, None),
                       137: (ct.AddressString, "chargeNumber"),
                       138: (ct.Tag, "interExchangeCarrierIndicator"),
                       139: (ct.OriginatingLineInformation, None),
                       140: (ct.SelectedCodec, None),
                       141: (ct.Tag, "wPSCallIndicator"),
                       142: (ct.UserToUserService1Information, None),
                       143: (ct.IMEISV, "callingSubscriberIMEISV"),
                       144: (ct.GlobalCallReference, None),
                       145: (ct.RoamingPriorityLevel, None),
                       146: (ct.Tag, "rTCIndicator"),
                       147: (ct.RTCSessionID, None),
                       148: (ct.RTCDefaultServiceHandling, None),
                       149: (ct.RTCFailureIndicator, None),
                       150: (ct.RTCNotInvokedReason, None),
                       151: (ct.AddressString,"calledDirectoryNumber"),
                       152: (ct.PChargingVector, "outgoingPChargingVector"),
                       153: (ct.IuCodec, None),
                       66: (ct.OriginatedCode, None),
                       121: (ct.Tag, "reroutingIndicator"),
                       122: (ct.Tag, "invocationOfCallHold"),
                       123: (ct.Tag, "retrievalOfHeldCall")
  }

    def __init__(self, tag=None, byte_string=None):
        super(MSOriginating, self).__init__(tag, byte_string)


class RoamingCallForwarding(CallModule):
    _data_tag_types = {0: (ct.TAC, None),
                       1: (ct.CallIDNumber, None),
                       2: (ct.RecordSequenceNumber, None),
                       3: (ct.TypeOfCallingSubscriber, None),
                       4: (ct.AddressString, "callingPartyNumber"),
                       5: (ct.AddressString, "calledPartyNumber"),
                       6: (ct.IMSI, "calledSubscriberIMSI"),
                       7: (ct.AddressString, "mobileStationRoamingNumber"),
                       8: (ct.DisconnectingParty, None),
                       9: (ct.Date, "dateForStartOfCharge"),
                       10: (ct.Time, "timeForStartOfCharge"),
                       11: (ct.Time, "timeForStopOfCharge"),
                       12: (ct.Time, "chargeableDuration"),
                       13: (ct.Time, "interruptionTime"),
                       14: (ct.Time, "timeFromRegisterSeizureToStartOfCharging"),
                       15: (ct.ChargedParty, None),
                       16: (ct.ChargingOrigin, None),
                       17: (ct.TariffClass, None),
                       18: (ct.TariffSwitchInd, None),
                       19: (ct.ExchangeIdentity, None),
                       20: (ct.AddressString, "mSCIdentification"),
                       21: (ct.Route, "outgoingRoute"),
                       22: (ct.Route, "incomingRoute"),
                       23: (ct.MiscellaneousInformation, None),
                       24: (ct.SubscriptionType, None),
                       25: (ct.CallPosition, None),
                       26: (ct.EosInfo, None),
                       27: (ct.InternalCauseAndLoc, None),
                       28: (ct.AddressString, "originalCalledNumber"),
                       29: (ct.AddressString, "redirectingNumber"),
                       30: (ct.RedirectionCounter, None),
                       31: (ct.Tag, "restartDuringCall"),
                       32: (ct.Tag, "restartDuringOutputIndicator"),
                       33: (ct.NumberOfMeterPulses, None),
                       34: (ct.C7ChargingMessage, None),
                       35: (ct.C7CHTMessage, "c7FirstCHTMessage"),
                       36: (ct.C7CHTMessage, "c7SecondCHTMessage"),
                       37: (ct.Tag, "iCIOrdered"),
                       38: (ct.OutputForSubscriber, None),
                       39: (ct.Tag, "lastPartialOutput"),
                       40: (ct.PartialOutputRecNum, None),
                       41: (ct.CallIDNumber, "relatedCallNumber"),
                       42: (ct.CUGInterlockCode, None),
                       43: (ct.Tag, "cUGOutgoingAccessIndicator"),
                       44: (ct.PresentationAndScreeningIndicator, None),
                       45: (ct.FaultCode, None),
                       46: (ct.Tag, "incompleteCallDataIndicator"),
                       47: (ct.MultimediaInformation, None),
                       48: (ct.SwitchIdentity, None),
                       49: (ct.NetworkCallReference, None),
                       50: (ct.Tag, "disconnectionDueToSystemRecovery"),
                       51: (ct.Tag, "forloppDuringOutputIndicator"),
                       52: (ct.Tag, "forloppReleaseDuringCall"),
                       53: (ct.GSMCallReferenceNumber, None),
                       54: (ct.AddressString, "mSCAddress"),
                       55: (ct.TransitCarrierInfo, "carrierInformationBackward"),
                       56: (ct.Tag, "originatingAccessISDN"),
                       57: (ct.CarrierInfo, "originatingCarrier"),
                       58: (ct.ChargeAreaCode, "originatingChargeArea"),
                       59: (ct.Tag, "terminatingAccessISDN"),
                       60: (ct.CarrierInfo, "terminatingCarrier"),
                       61: (ct.ChargeAreaCode, "terminatingChargeArea"),
                       62: (ct.AddressString, "contractorNumber"),
                       63: (ct.CarrierIdentificationCode, None),
                       64: (ct.CarrierInformation, None),
                       65: (ct.CarrierSelectionSubstitutionInformation, None),
                       66: (ct.AddressString, "chargeNumber"),
                       67: (ct.Tag, "interExchangeCarrierIndicator"),
                       68: (ct.OriginatingLineInformation, None),
                       69: (ct.UserToUserInformation, None),
                       70: (ct.GlobalCallReference, None),
                       71: (ct.Tag, "rTCIndicator"),
                       72: (ct.RTCSessionID, None),
                       73: (ct.RTCDefaultServiceHandling, None),
                       74: (ct.RTCFailureIndicator, None),
                       75: (ct.RTCNotInvokedReason, None),
                       76: (ct.AddressString, "mobileSubscriberNumberForHLRInterrogation"),
                       77: (ct.PChargingVector, "outgoingPChargingVector"),
                       102: (ct.OutputType, None),
                       121: (ct.Tag, "reroutingIndicator")
    }

    def __init__(self, tag=None, byte_string=None):
        super(RoamingCallForwarding, self).__init__(tag, byte_string)


class CallForwarding(CallModule):
    _data_tag_types = {0: (ct.TAC, None),
                       1: (ct.CallIDNumber, None),
                       2: (ct.RecordSequenceNumber, None),
                       3: (ct.TypeOfCallingSubscriber, None),
                       4: (ct.AddressString, "callingPartyNumber"),
                       5: (ct.AddressString, "calledPartyNumber"),
                       6: (ct.AddressString, "originalCalledNumber"),
                       7: (ct.AddressString, "redirectingNumber"),
                       8: (ct.RedirectionCounter, None),
                       9: (ct.AddressString, "redirectingSPN"),
                       10: (ct.IMSI, "redirectingIMSI"),
                       11: (ct.AddressString, "mobileStationRoamingNumber"),
                       12: (ct.DisconnectingParty, None),
                       13: (ct.Date, "dateForStartOfCharge"),
                       14: (ct.Time, "timeForStartOfCharge"),
                       15: (ct.Time, "timeForStopOfCharge"),
                       16: (ct.Time, "chargeableDuration"),
                       17: (ct.Time, "interruptionTime"),
                       18: (ct.Time, "timeFromRegisterSeizureToStartOfCharging"),
                       19: (ct.ChargedParty, None),
                       20: (ct.ChargingOrigin, None),
                       21: (ct.TariffClass, None),
                       22: (ct.TariffSwitchInd, None),
                       23: (ct.ExchangeIdentity, None),
                       24: (ct.AddressString, "mSCIdentification"),
                       25: (ct.Route, "outgoingRoute"),
                       26: (ct.Route, "incomingRoute"),
                       27: (ct.MiscellaneousInformation, None),
                       28: (ct.AddressString, "originatingLocationNumber"),
                       29: (ct.CallPosition, None),
                       30: (ct.EosInfo, None),
                       31: (ct.InternalCauseAndLoc, None),
                       32: (ct.Tag, "restartDuringCall"),
                       33: (ct.Tag, "restartDuringOutputIndicator"),
                       34: (ct.NumberOfMeterPulses, None),
                       35: (ct.C7ChargingMessage, None),
                       36: (ct.C7CHTMessage, "c7FirstCHTMessage"),
                       37: (ct.C7CHTMessage, "c7SecondCHTMessage"),
                       38: (ct.Tag, "iCIOrdered"),
                       39: (ct.OutputForSubscriber, None),
                       40: (ct.INMarkingOfMS, None),
                       41: (ct.Tag, "lastPartialOutput"),
                       42: (ct.PartialOutputRecNum, None),
                       43: (ct.CallIDNumber, "relatedCallNumber"),
                       44: (ct.CUGInterlockCode, None),
                       45: (ct.CUGIndex, None),
                       46: (ct.Tag, "cUGOutgoingAccessUsed"),
                       47: (ct.Tag, "cUGOutgoingAccessIndicator"),
                       48: (ct.RegionalServiceUsed, None),
                       49: (ct.ChargingOrigin, None),
                       50: (ct.PresentationAndScreeningIndicator, None),
                       51: (ct.FaultCode, None),
                       52: (ct.SubscriptionType, None),
                       53: (ct.Tag, "incompleteCallDataIndicator"),
                       54: (ct.Tag, "incompleteCompositeCDRIndicator"),
                       56: (ct.SwitchIdentity, None),
                       57: (ct.NetworkCallReference, None),
                       58: (ct.Tag, "disconnectionDueToSystemRecovery"),
                       59: (ct.Tag, "forloppDuringOutputIndicator"),
                       60: (ct.Tag, "forloppReleaseDuringCall"),
                       61: (ct.AddressString, "translatedNumber"),
                       62: (ct.Tag, "cAMELInitiatedCallForwarding"),
                       63: (ct.CAMELTDPData, "bCSMTDPData1"),
                       64: (ct.CAMELTDPData, "bCSMTDPData2"),
                       65: (ct.CAMELTDPData, "bCSMTDPData3"),
                       66: (ct.CAMELTDPData, "bCSMTDPData4"),
                       67: (ct.CAMELTDPData, "bCSMTDPData5"),
                       68: (ct.CAMELTDPData, "bCSMTDPData6"),
                       69: (ct.CAMELTDPData, "bCSMTDPData7"),
                       70: (ct.CAMELTDPData, "bCSMTDPData8"),
                       71: (ct.CAMELTDPData, "bCSMTDPData9"),
                       72: (ct.CAMELTDPData, "bCSMTDPData10"),
                       73: (ct.GSMCallReferenceNumber, None),
                       74: (ct.AddressString, "mSCAddress"),
                       75: (ct.ChargingIndicator, "aCMChargingIndicator"),
                       76: (ct.ChargingIndicator, "aNMChargingIndicator"),
                       77: (ct.TransitCarrierInfo, "carrierInformationBackward"),
                       78: (ct.ChargeInformation, None),
                       79: (ct.Date, "disconnectionDate"),
                       80: (ct.Time, "disconnectionTime"),
                       81: (ct.ChargeAreaCode, "exitPOICA"),
                       82: (ct.CarrierInfo, "originatingCarrier"),
                       83: (ct.ChargeAreaCode, "originatingChargeArea"),
                       84: (ct.Tag, "terminatingAccessISDN"),
                       85: (ct.CarrierInfo, "terminatingCarrier"),
                       86: (ct.ChargeAreaCode, "terminatingChargeArea"),
                       87: (ct.MobileUserClass1, "terminatingMobileUserClass1"),
                       88: (ct.MobileUserClass2, "terminatingMobileUserClass2"),
                       89: (ct.UserClass, "terminatingUserClass"),
                       90: (ct.Tag, "originatingAccessISDN"),
                       91: (ct.AddressString, "contractorNumber"),
                       92: (ct.AddressString, "calledPartyMNPInfo"),
                       93: (ct.CarrierIdentificationCode, None),
                       94: (ct.CarrierInformation, None),
                       95: (ct.CarrierSelectionSubstitutionInformation, None),
                       96: (ct.AddressString, "chargeNumber"),
                       97: (ct.Tag, "interExchangeCarrierIndicator"),
                       98: (ct.OriginatingLineInformation, None),
                       99: (ct.OptimalRoutingType, None),
                       100: (ct.Tag, "optimalRoutingInvocationFailed"),
                       101: (ct.UserToUserInformation, None),
                       102: (ct.OutputType, None),
                       103: (ct.MultimediaInformation, None),
                       104: (ct.GlobalCallReference, None),
                       105: (ct.Tag, "rTCIndicator"),
                       106: (ct.RTCSessionID, None),
                       107: (ct.RTCDefaultServiceHandling, None),
                       108: (ct.RTCFailureIndicator, None),
                       109: (ct.RTCNotInvokedReason, None),
                       110: (ct.AddressString, "calledDirectoryNumber"),
                       111: (ct.PChargingVector, "outgoingPChargingVector"),
                       55: (ct.OriginatedCode, None),
                       121: (ct.Tag, "reroutingIndicator")
    }

    def __init__(self, tag=None, byte_string=None):
        super(CallForwarding, self).__init__(tag, byte_string)


class MSTerminating(CallModule):  # ACA!!!
    _data_tag_types = {0: (ct.TAC, None),
                       1: (ct.CallIDNumber, None),
                       2: (ct.RecordSequenceNumber, None),
                       3: (ct.TypeOfCallingSubscriber, None),
                       4: (ct.AddressString, "callingPartyNumber"),
                       5: (ct.AddressString, "calledPartyNumber"),
                       6: (ct.IMSI, "calledSubscriberIMSI"),
                       7: (ct.IMEI, "calledSubscriberIMEI"),
                       8: (ct.AddressString, "mobileStationRoamingNumber"),
                       9: (ct.DisconnectingParty, None),
                       10: (ct.Date, "dateForStartOfCharge"),
                       11: (ct.Time, "timeForStartOfCharge"),
                       12: (ct.Time, "timeForStopOfCharge"),
                       13: (ct.Time, "chargeableDuration"),
                       14: (ct.Time, "interruptionTime"),
                       15: (ct.Time, "timeFromRegisterSeizureToStartOfCharging"),
                       16: (ct.ChargedParty, None),
                       17: (ct.ChargingOrigin, None),
                       18: (ct.TariffClass, None),
                       19: (ct.TariffSwitchInd, None),
                       20: (ct.ExchangeIdentity, None),
                       21: (ct.AddressString, "mSCIdentification"),
                       22: (ct.Route, "outgoingRoute"),
                       23: (ct.Route, "incomingRoute"),
                       24: (ct.ChannelAllocationPriorityLevel, None),
                       25: (ct.AddressString, "terminatingLocationNumber"),
                       26: (ct.Time, "timeForTCSeizureCalled"),
                       27: (ct.LocationInformation, "firstCalledLocationInformation"),
                       28: (ct.LocationInformation, "lastCalledLocationInformation"),
                       29: (ct.TeleServiceCode, None),
                       30: (ct.BearerServiceCode, None),
                       31: (ct.TransparencyIndicator, None),
                       32: (ct.FirstRadioChannelUsed, None),
                       33: (ct.CallPosition, None),
                       34: (ct.EosInfo, None),
                       35: (ct.InternalCauseAndLoc, None),
                       36: (ct.AddressString, "originalCalledNumber"),
                       37: (ct.AddressString, "redirectingNumber"),
                       38: (ct.RedirectionCounter, None),
                       39: (ct.SelectedCodec, None),
                       40: (ct.UserToUserInformation, None),
                       41: (ct.Tag, "restartDuringCall"),
                       42: (ct.Tag, "restartDuringOutputIndicator"),
                       43: (ct.Tag, "dTMFUsed"),
                       44: (ct.Tag, "iCIOrdered"),
                       45: (ct.OutputForSubscriber, None),
                       46: (ct.Tag, "lastPartialOutput"),
                       47: (ct.PartialOutputRecNum, None),
                       48: (ct.CallIDNumber, "relatedCallNumber"),
                       49: (ct.Tag, "acceptanceOfCallWaiting"),
                       50: (ct.MiscellaneousInformation, None),
                       51: (ct.CUGInterlockCode, None),
                       52: (ct.CUGIndex, None),
                       53: (ct.Tag, "cUGIncomingAccessUsed"),
                       54: (ct.RegionalServiceUsed, None),
                       55: (ct.ChargingOrigin, "regionDependentChargingOrigin"),
                       56: (ct.SSCode, None),
                       57: (ct.PresentationAndScreeningIndicator, None),
                       58: (ct.RadioChannelProperty, None),
                       59: (ct.FaultCode, None),
                       60: (ct.IntermediateRate, None),
                       61: (ct.SpeechCoderVersion, "firstAssignedSpeechCoderVersion"),
                       62: (ct.SpeechCoderPreferenceList, None),
                       63: (ct.SubscriptionType, None),
                       64: (ct.Tag, "incompleteCallDataIndicator"),
                       65: (ct.AddressString, "mSCAddress"),
                       66: (ct.SwitchIdentity, None),
                       67: (ct.NetworkCallReference, None),
                       68: (ct.FrequencyBandSupported, None),
                       69: (ct.Tag, "disconnectionDueToSystemRecovery"),
                       70: (ct.Tag, "forloppDuringOutputIndicator"),
                       71: (ct.Tag, "forloppReleaseDuringCall"),
                       72: (ct.AccountCode, None),
                       73: (ct.GSMCallReferenceNumber, None),
                       74: (ct.EMLPPPriorityLevel, None),
                       75: (ct.PositionAccuracy, None),
                       76: (ct.UserTerminalPosition, None),
                       77: (ct.ChannelCodings, "acceptableChannelCodings"),
                       78: (ct.Route, "outgoingAssignedRoute"),
                       79: (ct.ChannelCodings, "channelCodingUsed"),
                       80: (ct.Tag, "multimediaCall"),
                       81: (ct.AddressString, "gsmSCFAddress"),
                       82: (ct.FixedNetworkUserRate, "fNURRequested"),
                       83: (ct.AirInterfaceUserRate, "aIURRequested"),
                       84: (ct.NumberOfChannels, "numberOfChannelsRequested"),
                       85: (ct.BSSMAPCauseCode, None),
                       86: (ct.BitRate, "guaranteedBitRate"),
                       87: (ct.TariffClass, None),
                       88: (ct.RANAPCauseCode, None),
                       89: (ct.TargetRNCid, "rNCidOfFirstRNC"),
                       90: (ct.BitRate, "maxBitRateDownlink"),
                       91: (ct.BitRate, "maxBitRateUplink"),
                       92: (ct.TransferDelay, None),
                       93: (ct.DeliveryOfErroneousSDU, "deliveryOfErroneousSDU1"),
                       94: (ct.DeliveryOfErroneousSDU, "deliveryOfErroneousSDU2"),
                       95: (ct.DeliveryOfErroneousSDU, "deliveryOfErroneousSDU3"),
                       96: (ct.ErrorRatio, "residualBitErrorRatio1"),
                       97: (ct.ErrorRatio, "residualBitErrorRatio2"),
                       98: (ct.ErrorRatio, "residualBitErrorRatio3"),
                       99: (ct.ErrorRatio, "sDUErrorRatio1"),
                       100: (ct.ErrorRatio, "sDUErrorRatio2"),
                       101: (ct.ErrorRatio, "sDUErrorRatio3"),
                       102: (ct.OutputType, None),
                       103: (ct.ChargingIndicator, "aCMChargingIndicator"),
                       104: (ct.ChargingIndicator, "aNMChargingIndicator"),
                       105: (ct.ChargeInformation, None),
                       106: (ct.Date, "disconnectionDate"),
                       107: (ct.Time, "disconnectionTime"),
                       108: (ct.Tag, "internationalCallIndicator"),
                       109: (ct.MobileUserClass1, None),
                       110: (ct.MobileUserClass2, None),
                       111: (ct.CarrierInfo, "originatingCarrier"),
                       112: (ct.ChargeAreaCode, "originatingChargeArea"),
                       113: (ct.CarrierInfo, "terminatingCarrier"),
                       114: (ct.ChargeAreaCode, "terminatingChargeArea"),
                       115: (ct.UserClass, None),
                       116: (ct.IMEISV, "calledSubscriberIMEISV"),
                       117: (ct.GlobalCallReference, None),
                       118: (ct.IuCodec, None),
                       121: (ct.Tag, "reroutingIndicator"),
                       122: (ct.Tag, "invocationOfCallHold"),
                       123: (ct.Tag, "retrievalOfHeldCall")
    }

    def __init__(self, tag=None, byte_string=None):
        super(MSTerminating, self).__init__(tag, byte_string)


class MSOriginatingSMSinMSC(CallModule):
    _data_tag_types = {0: (ct.TAC, None),
                       1: (ct.CallIDNumber, None),
                       2: (ct.RecordSequenceNumber, None),
                       3: (ct.TypeOfCallingSubscriber, None),
                       4: (ct.AddressString, "callingPartyNumber"),
                       5: (ct.IMSI, "callingSubscriberIMSI"),
                       6: (ct.IMEI, "callingSubscriberIMEI"),
                       7: (ct.Date, "dateForStartOfCharge"),
                       8: (ct.Time, "timeForStartOfCharge"),
                       9: (ct.ChargedParty, None),
                       10: (ct.ChargingOrigin, None),
                       11: (ct.ExchangeIdentity, None),
                       12: (ct.AddressString, "mSCIdentification"),
                       13: (ct.Route, "incomingRoute"),
                       14: (ct.LocationInformation, "firstCallingLocationInformation"),
                       15: (ct.TeleServiceCode, None),
                       16: (ct.AddressString, "serviceCentreAddress"),
                       17: (ct.IMEISV, "callingSubscriberIMEISV"),
                       19: (ct.Tag, "iCIOrdered"),
                       20: (ct.OutputForSubscriber, None),
                       21: (ct.MiscellaneousInformation, None),
                       22: (ct.RegionalServiceUsed, None),
                       23: (ct.ChargingOrigin, "regionDependentChargingOrigin"),
                       24: (ct.ChannelAllocationPriorityLevel, None),
                       25: (ct.FrequencyBandSupported, None),
                       26: (ct.Tag, "incompleteCallDataIndicator"),
                       27: (ct.Tag, "restartDuringOutputIndicator"),
                       28: (ct.Tag, "forloppDuringOutputIndicator"),
                       29: (ct.PositionAccuracy, None),
                       30: (ct.UserTerminalPosition, None),
                       31: (ct.SwitchIdentity, None),
                       32: (ct.AddressStringExtended, "destinationAddress"),
                       33: (ct.MessageReference, None),
                       34: (ct.MessageTypeIndicator, None),
                       35: (ct.TargetRNCid, "rNCidOfFirstRNC"),
                       36: (ct.CAMELTDPData, "bCSMTDPData1"),
                       37: (ct.AddressString, "cAMELCallingPartyNumber"),
                       38: (ct.AddressStringExtended, "cAMELDestinationAddress"),
                       39: (ct.AddressString, "cAMELSMSCAddress"),
                       40: (ct.DefaultSMS_Handling, None),
                       41: (ct.FreeFormatData, None),
                       42: (ct.SMSResult, None),
                       43: (ct.GSMCallReferenceNumber, "sMSReferenceNumber"),
                       44: (ct.AddressString, "mSCAddress"),
                       45: (ct.Tag, "rTCIndicator"),
                       46: (ct.RTCSessionID, None),
                       47: (ct.RTCDefaultServiceHandling, None),
                       48: (ct.RTCFailureIndicator, None),
                       49: (ct.RTCNotInvokedReason, None),
                       50: (ct.Tag, "mCASMSIndicator"),
                       51: (ct.AddressString, "reroutedToServiceCentreAddress"),
                       102: (ct.OutputType, None)
    }

    def __init__(self, tag=None, byte_string=None):
        super(MSOriginatingSMSinMSC, self).__init__(tag, byte_string)


class MSOriginatingSMSinSMS_IWMSC(CallModule):
    _data_tag_types = {0: (ct.TAC, None),
                       1: (ct.CallIDNumber, None),
                       2: (ct.RecordSequenceNumber, None),
                       3: (ct.AddressString, "callingPartyNumber"),
                       4: (ct.Date, "dateForStartOfCharge"),
                       5: (ct.Time, "timeForStartOfCharge"),
                       6: (ct.ChargedParty, None),
                       7: (ct.ExchangeIdentity, None),
                       8: (ct.AddressString, "mSCIdentification"),
                       9: (ct.TeleServiceCode, None),
                       10: (ct.AddressString, "serviceCentreAddress"),
                       11: (ct.MiscellaneousInformation, None),
                       12: (ct.Tag, "incompleteCallDataIndicator"),
                       13: (ct.Tag, "restartDuringOutputIndicator"),
                       14: (ct.Tag, "forloppDuringOutputIndicator"),
                       15: (ct.SwitchIdentity, None),
                       102: (ct.OutputType, None)
    }

    def __init__(self, tag=None, byte_string=None):
        super(MSOriginatingSMSinSMS_IWMSC, self).__init__(tag, byte_string)


class MSTerminatingSMSinMSC(CallModule):
    _data_tag_types = {0: (ct.TAC, None),
                       1: (ct.CallIDNumber, None),
                       2: (ct.RecordSequenceNumber, None),
                       3: (ct.AddressString, "calledPartyNumber"),
                       4: (ct.IMSI, "calledSubscriberIMSI"),
                       5: (ct.IMEI, "calledSubscriberIMEI"),
                       6: (ct.Date, "dateForStartOfCharge"),
                       7: (ct.Time, "timeForStartOfCharge"),
                       8: (ct.Time, "originForCharging"),
                       9: (ct.ChargedParty, None),
                       10: (ct.ExchangeIdentity, None),
                       11: (ct.AddressString, "mSCIdentification"),
                       12: (ct.Route, "outgoingRoute"),
                       13: (ct.LocationInformation, "firstCalledLocationInformation"),
                       14: (ct.TeleServiceCode, None),
                       15: (ct.AddressString, "serviceCentreAddress"),
                       18: (ct.Tag, "iCIOrdered"),
                       19: (ct.OutputForSubscriber, None),
                       20: (ct.MiscellaneousInformation, None),
                       21: (ct.RegionalServiceUsed, None),
                       22: (ct.ChargingOrigin, "regionDependentChargingOrigin"),
                       23: (ct.ChannelAllocationPriorityLevel, None),
                       24: (ct.Tag, "incompleteCallDataIndicator"),
                       25: (ct.Tag, "restartDuringOutputIndicator"),
                       26: (ct.FrequencyBandSupported, None),
                       27: (ct.Tag, "forloppDuringOutputIndicator"),
                       28: (ct.NumberOfShortMessage, None),
                       29: (ct.LocationInformation, "lastCalledLocationInformation"),
                       30: (ct.PositionAccuracy, None),
                       31: (ct.UserTerminalPosition, None),
                       32: (ct.SwitchIdentity, None),
                       33: (ct.AddressStringExtended, "originatingAddress"),
                       34: (ct.MessageTypeIndicator, None),
                       35: (ct.TargetRNCid, "rNCidOfFirstRNC"),
                       36: (ct.CAMELTDPData, "bCSMTDPData1"),
                       37: (ct.DefaultSMS_Handling, None),
                       38: (ct.FreeFormatData, None),
                       39: (ct.SMSResult, None),
                       40: (ct.GSMCallReferenceNumber, "sMSReferenceNumber"),
                       41: (ct.AddressString, "mSCAddress"),
                       42: (ct.AddressStringExtended, "cAMELOriginatingAddress"),
                       43: (ct.IMEISV, "calledSubscriberIMEISV"),
                       44: (ct.Tag, "rTCIndicator"),
                       45: (ct.RTCSessionID, None),
                       46: (ct.RTCDefaultServiceHandling, None),
                       47: (ct.RTCFailureIndicator, None),
                       48: (ct.RTCNotInvokedReason, None),
                       102: (ct.OutputType, None)
    }

    def __init__(self, tag=None, byte_string=None):
        super(MSTerminatingSMSinMSC, self).__init__(tag, byte_string)


class MSTerminatingSMSinSMS_GMSC(CallModule):
    _data_tag_types = {0: (ct.TAC, None),
                       1: (ct.CallIDNumber, None),
                       2: (ct.RecordSequenceNumber, None),
                       3: (ct.AddressString, "calledPartyNumber"),
                       4: (ct.IMSI, "calledSubscriberIMSI"),
                       5: (ct.AddressString, "mobileStationRoamingNumber"),
                       6: (ct.Date, "dateForStartOfCharge"),
                       7: (ct.Time, "timeForStartOfCharge"),
                       8: (ct.ChargedParty, None),
                       9: (ct.ExchangeIdentity, None),
                       10: (ct.AddressString, "mSCIdentification"),
                       11: (ct.TeleServiceCode, None),
                       12: (ct.AddressString, "serviceCentreAddress"),
                       13: (ct.AddressString, "mSCNumber"),
                       14: (ct.MiscellaneousInformation, None),
                       15: (ct.Tag, "incompleteCallDataIndicator"),
                       16: (ct.Tag, "restartDuringOutputIndicator"),
                       17: (ct.Tag, "forloppDuringOutputIndicator"),
                       18: (ct.NumberOfShortMessage, None),
                       19: (ct.SwitchIdentity, None),
                       102: (ct.OutputType, None)
    }

    def __init__(self, tag=None, byte_string=None):
        super(MSTerminatingSMSinSMS_GMSC, self).__init__(tag, byte_string)


class SSProcedure(CallModule):
    _data_tag_types = {0: (ct.TAC, None),
                       1: (ct.CallIDNumber, None),
                       2: (ct.RecordSequenceNumber, None),
                       3: (ct.TypeOfCallingSubscriber, None),
                       4: (ct.AddressString, "callingPartyNumber"),
                       5: (ct.IMSI, "callingSubscriberIMSI"),
                       6: (ct.IMEI, "callingSubscriberIMEI"),
                       7: (ct.Date, "dateForStartOfCharge"),
                       8: (ct.Time, "timeForStartOfCharge"),
                       9: (ct.ChargingOrigin, None),
                       10: (ct.ExchangeIdentity, None),
                       11: (ct.AddressString, "mSCIdentification"),
                       12: (ct.LocationInformation, "firstCallingLocationInformation"),
                       13: (ct.IMEISV, "callingSubscriberIMEISV"),
                       15: (ct.Tag, "iCIOrdered"),
                       16: (ct.OutputForSubscriber, None),
                       17: (ct.SSCode, None),
                       18: (ct.SSRequest, None),
                       19: (ct.MiscellaneousInformation, None),
                       20: (ct.RegionalServiceUsed, None),
                       21: (ct.ChargingOrigin, "regionDependentChargingOrigin"),
                       22: (ct.CallIDNumber, "relatedCallNumber"),
                       23: (ct.ApplicationIdentifier, "uSSDApplicationIdentifier"),
                       24: (ct.ServiceCode, "uSSDServiceCode"),
                       25: (ct.ProcedureCode, "uSSDProcedureCode"),
                       26: (ct.NumberOfOperations, "networkInitiatedUSSDOperations"),
                       27: (ct.OperationIdentifier, "uSSDOperationIdentifier"),
                       28: (ct.Tag, "incompleteCallDataIndicator"),
                       29: (ct.Tag, "restartDuringOutputIndicator"),
                       30: (ct.FrequencyBandSupported, None),
                       31: (ct.Tag, "forloppDuringOutputIndicator"),
                       32: (ct.SwitchIdentity, None),
                       33: (ct.NetworkCallReference, None),
                       34: (ct.PositionAccuracy, None),
                       35: (ct.UserTerminalPosition, None),
                       36: (ct.TargetRNCid, "rNCidOfFirstRNC"),
                       37: (ct.GlobalCallReference, None),
                       102: (ct.OutputType, None)
    }

    def __init__(self, tag=None, byte_string=None):
        super(SSProcedure, self).__init__(tag, byte_string)


class TransitINOutgoingCall(CallModule):
    _data_tag_types = {0: (ct.TAC, None),
                       1: (ct.CallIDNumber, None),
                       2: (ct.RecordSequenceNumber, None),
                       3: (ct.Route, "outgoingRoute"),
                       4: (ct.SubscriptionType, None),
                       5: (ct.Tag, "incompleteCallDataIndicator"),
                       6: (ct.Tag, "incompleteCompositeCDRIndicator"),
                       7: (ct.Tag, "lastPartialOutput"),
                       8: (ct.PartialOutputRecNum, None),
                       9: (ct.Tag, "restartDuringOutputIndicator"),
                       10: (ct.ExchangeIdentity, None),
                       11: (ct.Tag, "restartDuringCall"),
                       12: (ct.NetworkCallReference, None),
                       13: (ct.Tag, "iCIOrdered"),
                       14: (ct.OutputForSubscriber, None),
                       15: (ct.SwitchIdentity, None),
                       16: (ct.Tag, "disconnectionDueToSystemRecovery"),
                       17: (ct.Tag, "forloppDuringOutputIndicator"),
                       18: (ct.TariffClass, None),
                       19: (ct.Tag, "forloppReleaseDuringCall"),
                       20: (ct.C7ChargingMessage, None),
                       21: (ct.C7CHTMessage, "c7FirstCHTMessage"),
                       22: (ct.C7CHTMessage, "c7SecondCHTMessage"),
                       23: (ct.AddressString, "contractorNumber"),
                       24: (ct.AddressString, "calledPartyMNPInfo"),
                       25: (ct.GlobalCallReference, None),
                       26: (ct.PChargingVector, "outgoingPChargingVector"),
                       102: (ct.OutputType, None)
    }

    def __init__(self, tag=None, byte_string=None):
        super(TransitINOutgoingCall, self).__init__(tag, byte_string)


class INIncomingCall(CallModule):
    _data_tag_types = {0: (ct.CallIDNumber, None),
                       1: (ct.SwitchIdentity, None),
                       2: (ct.NetworkCallReference, None),
                       3: (ct.INServiceTrigger, None),
                       4: (ct.SSFChargingCase, None),
                       5: (ct.TriggerData, "triggerData0"),
                       6: (ct.TriggerData, "triggerData1"),
                       7: (ct.TriggerData, "triggerData2"),
                       8: (ct.TriggerData, "triggerData3"),
                       9: (ct.TriggerData, "triggerData4"),
                       10: (ct.TriggerData, "triggerData5"),
                       11: (ct.TriggerData, "triggerData6"),
                       12: (ct.TriggerData, "triggerData7"),
                       13: (ct.RecordSequenceNumber, None),
                       14: (ct.Tag, "incompleteCallDataIndicator"),
                       15: (ct.Tag, "incompleteCallDataIndicator"),
                       16: (ct.Tag, "incompleteCompositeCDRIndicator"),
                       17: (ct.Tag, "lastPartialOutput"),
                       18: (ct.PartialOutputRecNum, None),
                       19: (ct.Tag, "restartDuringOutputIndicator"),
                       20: (ct.Tag, "restartDuringCall"),
                       21: (ct.ExchangeIdentity, None),
                       22: (ct.Tag, "forloppDuringOutputIndicator"),
                       23: (ct.Tag, "forloppReleaseDuringCall"),
                       24: (ct.GSMCallReferenceNumber, None),
                       25: (ct.AddressString, "mSCAddress"),
                       26: (ct.DefaultCallHandling, None),
                       27: (ct.DefaultCallHandling, "defaultCallHandling2"),
                       28: (ct.LevelOfCAMELService, None),
                       29: (ct.GlobalCallReference, None),
                       102: (ct.OutputType, None)
    }

    def __init__(self, tag=None, byte_string=None):
        super(INIncomingCall, self).__init__(tag, byte_string)


class INOutgoingCall(CallModule):
    _data_tag_types = {0: (ct.CallIDNumber, None),
                       1: (ct.SwitchIdentity, None),
                       2: (ct.NetworkCallReference, None),
                       3: (ct.INServiceTrigger, None),
                       4: (ct.SSFChargingCase, None),
                       5: (ct.TriggerData, "triggerData0"),
                       6: (ct.TriggerData, "triggerData1"),
                       7: (ct.TriggerData, "triggerData2"),
                       8: (ct.TriggerData, "triggerData3"),
                       9: (ct.TriggerData, "triggerData4"),
                       10: (ct.TriggerData, "triggerData5"),
                       11: (ct.TriggerData, "triggerData6"),
                       12: (ct.TriggerData, "triggerData7"),
                       13: (ct.RecordSequenceNumber, None),
                       14: (ct.Tag, "disconnectionDueToSystemRecovery"),
                       15: (ct.Tag, "incompleteCallDataIndicator"),
                       16: (ct.Tag, "incompleteCompositeCDRIndicator"),
                       17: (ct.Tag, "lastPartialOutput"),
                       18: (ct.PartialOutputRecNum, None),
                       19: (ct.Tag, "restartDuringOutputIndicator"),
                       20: (ct.Tag, "restartDuringCall"),
                       21: (ct.ExchangeIdentity, None),
                       22: (ct.Tag, "forloppDuringOutputIndicator"),
                       23: (ct.Tag, "forloppReleaseDuringCall"),
                       24: (ct.GSMCallReferenceNumber, None),
                       25: (ct.AddressString, "mSCAddress"),
                       26: (ct.DefaultCallHandling, None),
                       27: (ct.DefaultCallHandling, "defaultCallHandling2"),
                       28: (ct.LevelOfCAMELService, None),
                       29: (ct.Tag, "gsmSCFInitiatedCallIndicator"),
                       29: (ct.GlobalCallReference, None),
                       102: (ct.OutputType, None)
    }

    def __init__(self, tag=None, byte_string=None):
        super(INOutgoingCall, self).__init__(tag, byte_string)


class ISDNOriginating(CallModule):
    _data_tag_types = {0: (ct.TrafficActivityCode, None),
                       1: (ct.CallIDNumber, None),
                       2: (ct.RecordSequenceNumber, None),
                       3: (ct.TypeOfCallingSubscriber, None),
                       4: (ct.AddressString, "chargedCallingPartyNumber"),
                       5: (ct.AddressString, "calledPartyNumber"),
                       6: (ct.DisconnectingParty, None),
                       7: (ct.Date, "dateForStartOfCharge"),
                       8: (ct.Time, "timeForStartOfCharge"),
                       9: (ct.Time, "timeForStopOfCharge"),
                       10: (ct.Time, "chargeableDuration"),
                       11: (ct.Time, "interruptionTime"),
                       12: (ct.TariffClass, None),
                       13: (ct.TariffSwitchInd, None),
                       14: (ct.ExchangeIdentity, None),
                       15: (ct.Route, "outgoingRoute"),
                       16: (ct.CallPosition, None),
                       17: (ct.Tag, "restartDuringCall"),
                       18: (ct.Tag, "restartDuringOutputIndicator"),
                       19: (ct.Tag, "lastPartialOutput"),
                       20: (ct.PartialOutputRecNum, None),
                       21: (ct.CUGInterlockCode, None),
                       22: (ct.CUGIndex, None),
                       23: (ct.PresentationAndScreeningIndicator, None),
                       24: (ct.Tag, "incompleteCallDataIndicator"),
                       25: (ct.NetworkCallReference, None),
                       26: (ct.Tag, "disconnectionDueToSystemRecovery"),
                       27: (ct.Tag, "forloppDuringOutputIndicator"),
                       28: (ct.CauseCode, None),
                       29: (ct.LocationCode, None),
                       30: (ct.AddressString, "networkProvidedCallingPartyNumber"),
                       31: (ct.AddressString, "calledPartyMNPInfo"),
                       32: (ct.Tag, "callingPartyNumberSpecialArrangementInd"),
                       33: (ct.AddressString, "userProvidedCallingPartyNumber"),
                       34: (ct.Tag, "forloppReleaseDuringCall"),
                       35: (ct.ChargedParty, None),
                       36: (ct.Tag, "callAttemptIndicator"),
                       37: (ct.Counter, "flexibleCounter1"),
                       38: (ct.Counter, "flexibleCounter2"),
                       39: (ct.Counter, "flexibleCounter3"),
                       40: (ct.Counter, "flexibleCounter4"),
                       41: (ct.Counter, "flexibleCounter5"),
                       42: (ct.Counter, "flexibleCounter6"),
                       43: (ct.Counter, "flexibleCounter7"),
                       44: (ct.Counter, "flexibleCounter8"),
                       45: (ct.CallAttemptState, None),
                       46: (ct.TypeOfSignalling, None),
                       47: (ct.TypeOfCalledSubscriber, None),
                       48: (ct.EndToEndAccessDataMap, None),
                       49: (ct.UserToUserService1Information, None),
                       50: (ct.SwitchIdentity, None),
                       51: (ct.AoCCurrencyAmountSent, None),
                       52: (ct.GlobalCallReference, None),
                       53: (ct.PChargingVector, "outgoingPChargingVector"),
                       102: (ct.OutputType, None)
    }

    def __init__(self, tag=None, byte_string=None):
        super(ISDNOriginating, self).__init__(tag, byte_string)


class ISDNCallForwarding(CallModule):
    _data_tag_types = {0: (ct.TrafficActivityCode, None),
                       1: (ct.CallIDNumber, None),
                       2: (ct.RecordSequenceNumber, None),
                       3: (ct.TypeOfCallingSubscriber, None),
                       4: (ct.AddressString, "chargedCallingPartyNumber"),
                       5: (ct.AddressString, "calledPartyNumber"),
                       6: (ct.DisconnectingParty, None),
                       7: (ct.Date, "dateForStartOfCharge"),
                       8: (ct.Time, "timeForStartOfCharge"),
                       9: (ct.Time, "timeForStopOfCharge"),
                       10: (ct.Time, "chargeableDuration"),
                       11: (ct.Time, "interruptionTime"),
                       12: (ct.TariffClass, None),
                       13: (ct.TariffSwitchInd, None),
                       14: (ct.ExchangeIdentity, None),
                       15: (ct.Route, "outgoingRoute"),
                       16: (ct.CallPosition, None),
                       17: (ct.AddressString, "originalCalledNumber"),
                       18: (ct.AddressString, "redirectingNumber"),
                       19: (ct.Tag, "restartDuringCall"),
                       20: (ct.Tag, "restartDuringOutputIndicator"),
                       21: (ct.Tag, "lastPartialOutput"),
                       22: (ct.PartialOutputRecNum, None),
                       23: (ct.CUGInterlockCode, None),
                       24: (ct.CUGIndex, None),
                       25: (ct.PresentationAndScreeningIndicator, None),
                       26: (ct.Tag, "incompleteCallDataIndicator"),
                       27: (ct.NetworkCallReference, None),
                       28: (ct.Tag, "disconnectionDueToSystemRecovery"),
                       29: (ct.Tag, "forloppDuringOutputIndicator"),
                       30: (ct.CauseCode, None),
                       31: (ct.LocationCode, None),
                       32: (ct.AddressString, "networkProvidedCallingPartyNumber"),
                       33: (ct.AddressString, "callingPartyNumber"),
                       34: (ct.AddressString, "calledPartyMNPInfo"),
                       35: (ct.Tag, "forloppReleaseDuringCall"),
                       36: (ct.ChargedParty, None),
                       37: (ct.Tag, "callAttemptIndicator"),
                       38: (ct.Counter, "flexibleCounter1"),
                       39: (ct.Counter, "flexibleCounter2"),
                       40: (ct.Counter, "flexibleCounter3"),
                       41: (ct.Counter, "flexibleCounter4"),
                       42: (ct.Counter, "flexibleCounter5"),
                       43: (ct.Counter, "flexibleCounter6"),
                       44: (ct.Counter, "flexibleCounter7"),
                       45: (ct.Counter, "flexibleCounter8"),
                       46: (ct.CallAttemptState, None),
                       47: (ct.TypeOfSignalling, None),
                       48: (ct.TypeOfCalledSubscriber, None),
                       49: (ct.EndToEndAccessDataMap, None),
                       50: (ct.UserToUserService1Information, None),
                       51: (ct.SwitchIdentity, None),
                       52: (ct.AoCCurrencyAmountSent, None),
                       53: (ct.GlobalCallReference, None),
                       55: (ct.PChargingVector, "outgoingPChargingVector"),
                       102: (ct.OutputType, None)
    }

    def __init__(self, tag=None, byte_string=None):
        super(ISDNCallForwarding, self).__init__(tag, byte_string)


class ISDNSSProcedure(CallModule):
    _data_tag_types = {0: (ct.TrafficActivityCode, None),
                       1: (ct.CallIDNumber, None),
                       2: (ct.RecordSequenceNumber, None),
                       3: (ct.TypeOfCallingSubscriber, None),
                       4: (ct.Date, "dateForStartOfCharge"),
                       5: (ct.Time, "timeForStartOfCharge"),
                       6: (ct.TariffClass, None),
                       7: (ct.ExchangeIdentity, None),
                       8: (ct.Tag, "restartDuringOutputIndicator"),
                       9: (ct.Tag, "incompleteCallDataIndicator"),
                       10: (ct.Tag, "forloppDuringOutputIndicator"),
                       11: (ct.AddressString, "servedSubscriberNumber"),
                       12: (ct.ChargedParty, None),
                       13: (ct.SwitchIdentity, None),
                       102: (ct.OutputType, None)
    }

    def __init__(self, tag=None, byte_string=None):
        super(ISDNSSProcedure, self).__init__(tag, byte_string)


class SCFChargingOutput(CallModule):
    _data_tag_types = {0: (ct.CallIDNumber, None),
                       1: (ct.ExchangeIdentity, None),
                       2: (ct.GSMCallReferenceNumber, None),
                       3: (ct.Tag, "restartDuringCall"),
                       4: (ct.Tag, "restartDuringOutputIndicator"),
                       5: (ct.Tag, "lastPartialOutput"),
                       6: (ct.PartialOutputRecNum, None),
                       7: (ct.SwitchIdentity, None),
                       8: (ct.Tag, "disconnectionDueToSystemRecovery"),
                       9: (ct.Tag, "forloppDuringOutputIndicator"),
                       10: (ct.Tag, "forloppReleaseDuringCall"),
                       11: (ct.RecordSequenceNumber, None),
                       12: (ct.Tag, "incompleteCallDataIndicator"),
                       13: (ct.AddressString, "mSCAddress"),
                       13: (ct.Date, "date"),
                       102: (ct.OutputType, None)
    }

    def __init__(self, tag=None, byte_string=None):
        super(SCFChargingOutput, self).__init__(tag, byte_string)


class LocationServices(CallModule):
    _data_tag_types = {0: (ct.TAC, None),
                       1: (ct.CallIDNumber, None),
                       2: (ct.RecordSequenceNumber, None),
                       3: (ct.TypeOfCallingSubscriber, None),
                       4: (ct.AddressString, "targetMSISDN"),
                       5: (ct.IMSI, "targetIMSI"),
                       6: (ct.IMEI, "targetIMEI"),
                       7: (ct.Date, "dateForStartOfCharge"),
                       8: (ct.Time, "timeForStartOfCharge"),
                       9: (ct.ExchangeIdentity, None),
                       10: (ct.AddressString, "mSCIdentification"),
                       11: (ct.MiscellaneousInformation, None),
                       12: (ct.Tag, "restartDuringOutputIndicator"),
                       13: (ct.Tag, "iCIOrdered"),
                       14: (ct.OutputForSubscriber, None),
                       15: (ct.Tag, "incompleteCallDataIndicator"),
                       16: (ct.SwitchIdentity, None),
                       17: (ct.NetworkCallReference, None),
                       18: (ct.Tag, "forloppDuringOutputIndicator"),
                       19: (ct.PositioningDelivery, None),
                       20: (ct.AddressString, "lCSClientIdentity"),
                       21: (ct.LCSClientType, None),
                       22: (ct.LocationEstimate, None),
                       23: (ct.AgeOfLocationEstimate, None),
                       24: (ct.SubscriberState, None),
                       25: (ct.AddressString, "mLCAddress"),
                       26: (ct.DecipheringKeys, None),
                       27: (ct.TypeOfLocationRequest, None),
                       28: (ct.LocationInformation, "firstTargetLocationInformation"),
                       29: (ct.LCSAccuracy, "horizontalAccuracy"),
                       30: (ct.ResponseTimeCategory, None),
                       31: (ct.LCSAccuracy, "verticalAccuracy"),
                       32: (ct.Tag, "verticalCoordinateRequest"),
                       33: (ct.UnsuccessfulPositioningDataReason, None),
                       34: (ct.LCSDeferredEventType, None),
                       35: (ct.IMEISV, "targetIMEISV"),
                       36: (ct.GlobalCallReference, None),
                       102: (ct.OutputType, None)
    }

    def __init__(self, tag=None, byte_string=None):
        super(LocationServices, self).__init__(tag, byte_string)
